# Site settings
title: My Travelog
subtitle: "Journal of [name]"
email: your-email@domain.com
description: "Make the footer happy by entering a short description about yourself here"
baseurl: ""
url: "http://katieball.me/travellog-theme"
twitter_username: "mektball"
github_username:  "roachhd"
instagram_username: "RoachHD"

# Build settings
markdown: kramdown
permalink: pretty

# Pagination
paginate: 5

# Sass
sass:
    style: :compressed

baseurl: http://roachhd.github.io/travellog-theme
